FROM node:latest

WORKDIR /migrate

COPY ./prisma/migrations ./prisma/migrations
COPY ./prisma/schema.prisma ./prisma/schema.prisma

RUN npx prisma -v

ENTRYPOINT [ "npx", "prisma", "migrate", "deploy" ]